/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.22
 * Generated at: 2019-07-22 20:17:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<title>Being Association - A Mumbai Based Theatre Group</title>\r\n");
      out.write("<meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\">\r\n");
      out.write("<meta content=\"theatre, book, natak, poem, story, shayar, author, writter, natak\" name=\"keywords\">\r\n");
      out.write("<meta content=\"This website is E library for books based on story poems by author writter shayar and written plays and natak\" name=\"description\">\r\n");
      out.write("\r\n");
      out.write("<!-- Favicons -->\r\n");
      out.write("<link href=\"img/favicon.png\" rel=\"icon\">\r\n");
      out.write("<link href=\"img/apple-touch-icon.png\" rel=\"apple-touch-icon\">\r\n");
      out.write("\r\n");
      out.write("<!-- Google Fonts -->\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,700,700i|Raleway:300,400,500,700,800\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap CSS File -->\r\n");
      out.write("<link href=\"lib/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- Libraries CSS Files -->\r\n");
      out.write("<link href=\"lib/font-awesome/css/font-awesome.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"lib/animate/animate.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"lib/venobox/venobox.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"lib/owlcarousel/assets/owl.carousel.min.css\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- Main Stylesheet File -->\r\n");
      out.write("<link href=\"css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- =======================================================\r\n");
      out.write("    Theme Name: Being Association \r\n");
      out.write("    Theme URL: \r\n");
      out.write("    Author: Ebook Team\r\n");
      out.write("    License: \r\n");
      out.write("  ======================================================= -->\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<!--==========================\r\n");
      out.write("    Header\r\n");
      out.write("  ============================-->\r\n");
      out.write("\t<header id=\"header\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div id=\"logo\" class=\"pull-left\">\r\n");
      out.write("\t\t\t\t<!-- Uncomment below if you prefer to use a text logo -->\r\n");
      out.write("\t\t\t\t<!-- <h1><a href=\"#main\">C<span>o</span>nf</a></h1>-->\r\n");
      out.write("\t\t\t\t<a href=\"#intro\" class=\"scrollto\"><img src=\"img/newLogo.png\"\r\n");
      out.write("\t\t\t\t\talt=\"\" title=\"\"></a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<nav id=\"nav-menu-container\">\r\n");
      out.write("\t\t\t\t<ul class=\"nav-menu\">\r\n");
      out.write("\t\t\t\t\t<li class=\"menu-active\"><a href=\"#intro\">Home</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#aboutUs\">About Us</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#speakers\">Our Work</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#gallery\">Gallery</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\" data-toggle=\"dropdown\">Sanhita Manch</a>\r\n");
      out.write("\t\t\t\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\" class=\"dropdown-item\">Sanhita Manch 2019</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\" class=\"dropdown-item\">Sanhita Manch 2018</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\" class=\"dropdown-item\">Sanhita Manch 2017</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#venue\">Upcoming Events</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#contact\">Contact</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">Donate</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"buy-tickets\"><a href=\"#\">login</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"buy-tickets\"><a href=\"#\">Register Now</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</nav>\r\n");
      out.write("\t\t\t<!-- #nav-menu-container -->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</header>\r\n");
      out.write("\t<!-- #header -->\r\n");
      out.write("\r\n");
      out.write("\t<!--==========================\r\n");
      out.write("    Intro Section\r\n");
      out.write("  ============================-->\r\n");
      out.write("\t<section id=\"intro\">\r\n");
      out.write("\t\t<div class=\"intro-container wow fadeIn\">\r\n");
      out.write("\t\t\t<h1 class=\"mb-4 pb-0\">\r\n");
      out.write("\t\t\t\tBeing Association<br> <span>A Mumbai Based Theatre Group</span>\r\n");
      out.write("\t\t\t</h1>\r\n");
      out.write("\t\t\t<!--       <a href=\"https://www.youtube.com/watch?v=jDDaplaOz7Q\" class=\"venobox play-btn mb-4\" data-vbtype=\"video\"\r\n");
      out.write("        data-autoplay=\"true\"></a>\r\n");
      out.write("      <a href=\"#about\" class=\"about-btn scrollto\">About The Event</a> -->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<main id=\"main\">\r\n");
      out.write("\t<section id=\"aboutUs\" class=\"wow fadeInUp\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"section-header\">\r\n");
      out.write("\t\t\t\t<h2>About Us</h2>\r\n");
      out.write("\t\t\t\t<p>Know us better</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-lg-12\">\r\n");
      out.write("\t\t\t\t<h2>About Us</h2>\r\n");
      out.write("\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t<b>A GROUP OF YOUNG ACTORS AND DIRECTORS TO ENGAGE, INSPIRE AND\r\n");
      out.write("\t\t\t\t\t\tCHALLENGE AUDIENCES WITH OUR WORK RANGING FROM THE CLASSICS TO THE\r\n");
      out.write("\t\t\t\t\t\tCONTEMPORARY</b>\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t<p>The Being Association theatre group was formed in 2013 by a\r\n");
      out.write("\t\t\t\t\tgroup of young fellow actors and directors to engage, inspire and\r\n");
      out.write("\t\t\t\t\tchallenge audiences with theatrical productions that range from the\r\n");
      out.write("\t\t\t\t\tclassics to contemporary works. From its inception, we have\r\n");
      out.write("\t\t\t\t\tproduced significant number of plays and performed at prominent art\r\n");
      out.write("\t\t\t\t\tplatforms of the country including the prestigious theatre\r\n");
      out.write("\t\t\t\t\tfestivals. We train and support the next generation of theatre\r\n");
      out.write("\t\t\t\t\tartists by conducting theatre workshops periodically under the\r\n");
      out.write("\t\t\t\t\tguidance of professionally trained and talented theatre\r\n");
      out.write("\t\t\t\t\tpractitioners. The occasional reading sessions by Being Association\r\n");
      out.write("\t\t\t\t\ttheatre group endeavours to stimulate the literary culture that\r\n");
      out.write("\t\t\t\t\tempowers both artists and the audience. Apart from staging our\r\n");
      out.write("\t\t\t\t\tplays, holding the reading sessions and conducting workshops, we\r\n");
      out.write("\t\t\t\t\talso organise an annual theatre festival to recognise, promote and\r\n");
      out.write("\t\t\t\t\tcirculate new original Hindi plays. We continue to enrich the\r\n");
      out.write("\t\t\t\t\ttheatre movement in the future. We continue to celebrate the\r\n");
      out.write("\t\t\t\t\tessential power of the theatre to illuminate the collective\r\n");
      out.write("\t\t\t\t\tconsciousness of humanity.</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t</section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!--==========================\r\n");
      out.write("      Work Section\r\n");
      out.write("    ============================-->\r\n");
      out.write("\t<section id=\"speakers\" class=\"wow fadeInUp\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"section-header\">\r\n");
      out.write("\t\t\t\t<h2>Our Work</h2>\r\n");
      out.write("\t\t\t\t<p>Here are some of our work</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-4 col-md-6\">\r\n");
      out.write("\t\t\t\t\t<div class=\"speaker\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"img/speakers/raatnaaaye.jpg\" alt=\"raat na aaye\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"img-fluid\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"details\">\r\n");
      out.write("\t\t\t\t\t\t\t<h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"speaker-details.html\">Raat Na Aaye</a>\r\n");
      out.write("\t\t\t\t\t\t\t</h3>\r\n");
      out.write("\t\t\t\t\t\t\t<p>BASED ON EUGINE OâNILâS LONG DAYS JOURNEY INTO NIGHT</p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-4 col-md-6\">\r\n");
      out.write("\t\t\t\t\t<div class=\"speaker\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"img/speakers/satthe.jpg\" alt=\"Satthe\" class=\"img-fluid\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"details\">\r\n");
      out.write("\t\t\t\t\t\t\t<h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"speaker-details.html\">Satthe</a>\r\n");
      out.write("\t\t\t\t\t\t\t</h3>\r\n");
      out.write("\t\t\t\t\t\t\t<p>IssÂ Kambakht SatheÂ Ka Kya Karien ?</p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-4 col-md-6\">\r\n");
      out.write("\t\t\t\t\t<div class=\"speaker\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"img/speakers/museum.jpg\" alt=\"Museum\" class=\"img-fluid\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"details\">\r\n");
      out.write("\t\t\t\t\t\t\t<h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"speaker-details.html\">Museum</a>\r\n");
      out.write("\t\t\t\t\t\t\t</h3>\r\n");
      out.write("\t\t\t\t\t\t\t<p>Directed by Rasika Agashe</p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t</section>\r\n");
      out.write("\r\n");
      out.write("\t<!--==========================\r\n");
      out.write("      Gallery Section\r\n");
      out.write("    ============================-->\r\n");
      out.write("\t<section id=\"gallery\" class=\"wow fadeInUp\">\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"section-header\">\r\n");
      out.write("\t\t\t\t<h2>Gallery</h2>\r\n");
      out.write("\t\t\t\t<p>Check our gallery from the recent events</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"owl-carousel gallery-carousel\">\r\n");
      out.write("\t\t\t<a href=\"img/gallery/1.jpg\" class=\"venobox\"\r\n");
      out.write("\t\t\t\tdata-gall=\"gallery-carousel\"><img src=\"img/gallery/1.jpg\" alt=\"\"></a>\r\n");
      out.write("\t\t\t<a href=\"img/gallery/2.jpg\" class=\"venobox\"\r\n");
      out.write("\t\t\t\tdata-gall=\"gallery-carousel\"><img src=\"img/gallery/2.jpg\" alt=\"\"></a>\r\n");
      out.write("\t\t\t<a href=\"img/gallery/3.jpg\" class=\"venobox\"\r\n");
      out.write("\t\t\t\tdata-gall=\"gallery-carousel\"><img src=\"img/gallery/3.jpg\" alt=\"\"></a>\r\n");
      out.write("\t\t\t<a href=\"img/gallery/4.jpg\" class=\"venobox\"\r\n");
      out.write("\t\t\t\tdata-gall=\"gallery-carousel\"><img src=\"img/gallery/4.jpg\" alt=\"\"></a>\r\n");
      out.write("\t\t\t<a href=\"img/gallery/5.jpg\" class=\"venobox\"\r\n");
      out.write("\t\t\t\tdata-gall=\"gallery-carousel\"><img src=\"img/gallery/5.jpg\" alt=\"\"></a>\r\n");
      out.write("\t\t\t<a href=\"img/gallery/6.JPG\" class=\"venobox\"\r\n");
      out.write("\t\t\t\tdata-gall=\"gallery-carousel\"><img src=\"img/gallery/6.JPG\" alt=\"\"></a>\r\n");
      out.write("\t\t\t<a href=\"img/gallery/7.jpg\" class=\"venobox\"\r\n");
      out.write("\t\t\t\tdata-gall=\"gallery-carousel\"><img src=\"img/gallery/7.jpg\" alt=\"\"></a>\r\n");
      out.write("\t\t\t<a href=\"img/gallery/8.jpg\" class=\"venobox\"\r\n");
      out.write("\t\t\t\tdata-gall=\"gallery-carousel\"><img src=\"img/gallery/8.jpg\" alt=\"\"></a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t</section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!--==========================\r\n");
      out.write("      Schedule Section\r\n");
      out.write("    ============================-->\r\n");
      out.write("\t<section id=\"venue\" class=\"section-with-bg\">\r\n");
      out.write("\t\t<div class=\"container wow fadeInUp\">\r\n");
      out.write("\t\t\t<div class=\"section-header\">\r\n");
      out.write("\t\t\t\t<h2>Upcoming Events</h2>\r\n");
      out.write("\t\t\t\t<p>Here is our event schedule</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"tab-content row justify-content-center\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- Schdule Day 1 -->\r\n");
      out.write("\t\t\t\t<div role=\"tabpanel\" class=\"col-lg-9 tab-pane fade show active\"\r\n");
      out.write("\t\t\t\t\tid=\"day-1\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"row schedule-item\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-2\">\r\n");
      out.write("\t\t\t\t\t\t\t<date>25/07/2019</date>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-10\">\r\n");
      out.write("\t\t\t\t\t\t\t<h4><a href=\"#\">Play 1</a></h4>\r\n");
      out.write("\t\t\t\t\t\t\t<p>Running Play 1</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"row schedule-item\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-2\">\r\n");
      out.write("\t\t\t\t\t\t\t<date>28/07/2019</date>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-10\">\r\n");
      out.write("\t\t\t\t\t\t\t<h4><a href=\"#\">Play 2</a></h4>\r\n");
      out.write("\t\t\t\t\t\t\t<p>Running Play 2</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"row schedule-item\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-2\">\r\n");
      out.write("\t\t\t\t\t\t\t<date>29/07/2019</date>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-10\">\r\n");
      out.write("\t\t\t\t\t\t\t<h4><a href=\"#\">Play 3</a></h4>\r\n");
      out.write("\t\t\t\t\t\t\t<p>Running Play 3</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t</section>\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!--==========================\r\n");
      out.write("      Contact Section\r\n");
      out.write("    ============================-->\r\n");
      out.write("\t<section id=\"contact\" class=\"section-bg wow fadeInUp\">\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"section-header\">\r\n");
      out.write("\t\t\t\t<h2>Contact Us</h2>\r\n");
      out.write("\t\t\t\t<p>Always stay in touch.</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"row contact-info\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"col-md-4\">\r\n");
      out.write("\t\t\t\t\t<div class=\"contact-address\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"ion-ios-location-outline\"></i>\r\n");
      out.write("\t\t\t\t\t\t<h3>Address</h3>\r\n");
      out.write("\t\t\t\t\t\t<address>abc, new street, mumbai, maharashtra</address>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"col-md-4\">\r\n");
      out.write("\t\t\t\t\t<div class=\"contact-phone\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"ion-ios-telephone-outline\"></i>\r\n");
      out.write("\t\t\t\t\t\t<h3>Phone Number</h3>\r\n");
      out.write("\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"tel:+155895548855\">+1 5589 55488 55</a>\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"col-md-4\">\r\n");
      out.write("\t\t\t\t\t<div class=\"contact-email\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"ion-ios-email-outline\"></i>\r\n");
      out.write("\t\t\t\t\t\t<h3>Email</h3>\r\n");
      out.write("\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"mailto:info@example.com\">info@example.com</a>\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"form\">\r\n");
      out.write("\t\t\t\t<div id=\"sendmessage\">Your message has been sent. Thank you!</div>\r\n");
      out.write("\t\t\t\t<div id=\"errormessage\"></div>\r\n");
      out.write("\t\t\t\t<form action=\"\" method=\"post\" role=\"form\" class=\"contactForm\">\r\n");
      out.write("\t\t\t\t\t<div class=\"form-row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group col-md-6\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" name=\"name\" class=\"form-control\" id=\"name\"\r\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\"Your Name\" data-rule=\"minlen:4\"\r\n");
      out.write("\t\t\t\t\t\t\t\tdata-msg=\"Please enter at least 4 chars\" />\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"validation\"></div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group col-md-6\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"email\" class=\"form-control\" name=\"email\" id=\"email\"\r\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\"Your Email\" data-rule=\"email\"\r\n");
      out.write("\t\t\t\t\t\t\t\tdata-msg=\"Please enter a valid email\" />\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"validation\"></div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" name=\"subject\"\r\n");
      out.write("\t\t\t\t\t\t\tid=\"subject\" placeholder=\"Subject\" data-rule=\"minlen:4\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-msg=\"Please enter at least 8 chars of subject\" />\r\n");
      out.write("\t\t\t\t\t\t<div class=\"validation\"></div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t<textarea class=\"form-control\" name=\"message\" rows=\"5\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-rule=\"required\" data-msg=\"Please write something for us\"\r\n");
      out.write("\t\t\t\t\t\t\tplaceholder=\"Message\"></textarea>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"validation\"></div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"text-center\">\r\n");
      out.write("\t\t\t\t\t\t<button type=\"submit\">Send Message</button>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\t<!-- #contact --> </main>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!--==========================\r\n");
      out.write("    Footer\r\n");
      out.write("  ============================-->\r\n");
      out.write("\t<footer id=\"footer\">\r\n");
      out.write("\t\t<div class=\"footer-top\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"social-links\">\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t       <h2>Follow us </h2>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"twitter\"><i class=\"fa fa-twitter\"></i></a> <a\r\n");
      out.write("\t\t\t\t\t\t\t\thref=\"#\" class=\"facebook\"><i class=\"fa fa-facebook\"></i></a> <a\r\n");
      out.write("\t\t\t\t\t\t\t\thref=\"#\" class=\"instagram\"><i class=\"fa fa-instagram\"></i></a> <a\r\n");
      out.write("\t\t\t\t\t\t\t\thref=\"#\" class=\"google-plus\"><i class=\"fa fa-google-plus\"></i></a>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"linkedin\"><i class=\"fa fa-linkedin\"></i></a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</footer>\r\n");
      out.write("\t<!-- #footer -->\r\n");
      out.write("\r\n");
      out.write("\t<a href=\"#\" class=\"back-to-top\"><i class=\"fa fa-angle-up\"></i></a>\r\n");
      out.write("\r\n");
      out.write("\t<!-- JavaScript Libraries -->\r\n");
      out.write("\t<script src=\"lib/jquery/jquery.min.js\"></script>\r\n");
      out.write("\t<script src=\"lib/jquery/jquery-migrate.min.js\"></script>\r\n");
      out.write("\t<script src=\"lib/bootstrap/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\t<script src=\"lib/easing/easing.min.js\"></script>\r\n");
      out.write("\t<script src=\"lib/superfish/hoverIntent.js\"></script>\r\n");
      out.write("\t<script src=\"lib/superfish/superfish.min.js\"></script>\r\n");
      out.write("\t<script src=\"lib/wow/wow.min.js\"></script>\r\n");
      out.write("\t<script src=\"lib/venobox/venobox.min.js\"></script>\r\n");
      out.write("\t<script src=\"lib/owlcarousel/owl.carousel.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Contact Form JavaScript File -->\r\n");
      out.write("\t<script src=\"contactform/contactform.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Template Main Javascript File -->\r\n");
      out.write("\t<script src=\"js/main.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
